### ISSUE TITLE
Portion of Providers Not Bidding on GPU Workloads When Model Specified

### ISSUE THREAD

**Issue by chainzero** [akash-network/support#106]
**_Summary_**

When an order is created for a GPU enabled SDL which includes a list of requested models - only a portion of providers with available, relevant inventory create bids.  The providers that have available inventory but that are not creating a bid show `insufficient capacity for reservation` in provider logs despite having sufficient capacity.

If the explicit GPU models are removed from the SDL the affected providers create bid successfully.  Identical SDL used in successful attempt with only the GPUs model list removed.

Other providers create bids on order receipt with GPU model list in SDL.  Thus this is a sporadic issue but appears consistent on affected providers.  Some providers never bid when model list is included.  Other providers bid without issue when GPU models are included.

**_Details_**

- GPU Testnet
- Tested Provider Version - v0.3.1-rc1
- Provider logs - https://transfer.sh/BzhMIeEuaS/provider-logs.tar.gz
- SDL used in testing - SDL within this Gist is the version that includes a GPU model list - same SDL with GPU list removed was used in the successful deployment example - https://gist.github.com/chainzero/6e7768ea0d948d81fe56e6b82ce1d84b
- Provider tested - akash143ypn84kuf379tv9wvcxsmamhj83d5pg2rfc8v
- Deployer address - akash1f53fp8kk470f7k26yr5gztd9npzpczqv4ufud7
- DSEQ of no bid generated problem deployment (SDL with GPU model list) - 364164
-DSEQ of successful order/bid received (SDL with no GPU model list but otherwise identical to failed attempt) - 364226

**_Provider Attributes_**

- As shown - the provider  is advertising GPU attribute of 3090 and thus should bid on the SDL that includes 3090 in GPU model list

```
provider-services query provider get akash143ypn84kuf379tv9wvcxsmamhj83d5pg2rfc8v
attributes:
- key: host
  value: akash
- key: tier
  value: community
- key: capabilities/gpu/vendor/nvidia/model/3090
  value: "true"
host_uri: https://provider.shimpa.org:8443
info:
  email: ""
  website: ""
owner: akash143ypn84kuf379tv9wvcxsmamhj83d5pg2rfc8v
```

**Comment by andy108369** [comment]
provider `0.3.2-rc4` fixes that
