### ISSUE TITLE
No such interface org.freedesktop.DBus.Properties

### ISSUE THREAD

**Issue by bitcoinmeetups** [akash-network/support#115]
Hi,

I'm Mr. Cherry, a very friendly guy. Issue:

Input:

AKASH_KEY_NAME=myWallet
echo $AKASH_KEY_NAME
AKASH_KEYRING_BACKEND=os
provider-services keys add $AKASH_KEY_NAME

Output:

myWallet
Error: No such interface “org.freedesktop.DBus.Properties” on object at path /

Environment: Raspberry PI 4, debian

**Comment by arno01** [comment]
Please use "file" or "test" (no password protection) keyring backend instead of the "os".

**Comment by bitcoinmeetups** [comment]
Ok I have tried replacing os with file or test. But I get the same results as before.
