### ISSUE TITLE
Audit for New Providers

### ISSUE THREAD

**Issue by Dverse9** [akash-network/support#117]
We have two new providers that need to be audited.

1. **Provider Name**: Otaku AI Designs
   - **Provider Address**: [provider.otakuaidesigns.com]
   
2. **Provider Name**: Akash Ai Network
   - **Provider Address**: [provider.akashainetwork.com]

Objectives
- Confirm the security of the providers
- Assess performance metrics
- Validate data integrity

**Comment by andy108369** [comment]
@Dverse9 apologies for that it took quite some time for me to start reviewing your providers.

Provider `Otaku AI Designs` isn't seem to be alive:

```
$ akash_providers |grep otakuaidesigns
"https://provider.otakuaidesigns.com:8443","akash19p4t9d069nashxre9jg6j60cqlqkvtht6egpc9","Otaku Ai Designs","true","amd64"
"https://provider.otakuaidesigns.com:8443","akash1g680cvzk2etcea23shfshtlm6x4japg569mq5m","Otaku Ai Designs","amd64"

$ nc -vz provider.otakuaidesigns.com 8443
nc: connect to provider.otakuaidesigns.com (47.207.33.190) port 8443 (tcp) failed: No route to host
```

Provider `Akash Ai Network` isn't seem to be alive:

```
$ akash_providers | grep akashainetwork
"https://provider.akashainetwork.com:8443","akash1jkck03xr9gnx8a5xud2h4jh0l7gu4a6yhxef6y","Akash Ai Network","true","amd64"
"https://provider.akashainetwork.com:8443","akash1tfhcspeqg03w3fzfutvknuhw36yv5rgwa87d8y","Akash Ai Network","amd64"

$ nc -vz provider.akashainetwork.com 8443
nc: connect to provider.akashainetwork.com (47.207.33.191) port 8443 (tcp) failed: No route to host
```

**Comment by andy108369** [comment]
both providers are down.
provider owner hasn't responded.
Closing.
