### ISSUE TITLE
docs: `Provider Build With GPU` duplicates lots of `Build a Cloud Provider`

### ISSUE THREAD

**Issue by andy108369** [akash-network/support#126]
https://docs.akash.network/providers/build-a-cloud-provider/provider-build-with-gpu duplicates lots of  https://docs.akash.network/providers/build-a-cloud-provider parts and the GPU parts should be either moved to the general `Build a Cloud Provider` doc or only GPU-specific bits need to present in `Provider Build With GPU`.

The primary reason is because otherwise it is difficult to maintain two provider build documents. (i.e. version bumps, notes, etc)

**Comment by chainzero** [comment]
The Akash provider docs have been consolidated so that all GPU and non-GPU enabled builds will follow a single set of instructions.
