### ISSUE TITLE
[Provider Audit] provider.validatornode.com

### ISSUE THREAD

**Issue by ourlink** [akash-network/support#150]
We have completed all the prerequisite steps as outlined below. If you could review/audit our provider we'd be appreciative.

Our contact information follows
1. Name                                                       **ValidatorNode**
2. Discord handle or Telegram handle        **ourlink_validatornode**
3. Contact email address                             **support@validatornode.com** 

**Provider details are -** provider.validatornode.com
**URL -** https://provider.validatornode.com:8443
**Address -** akash1whyxrlu7srr55kte4w2rxlmvzduj3je0gqlzjn

### 1. Make sure your provider has community provider attributes:

```
  Example:
  $ provider-services query provider get akash1<REDACTED> -o text
  ...
  attributes:
  ...
  - key: host
  value: akash
  - key: tier
  value: community

```

[Ref documentation:](https://docs.akash.network/providers/akash-audited-attributes#standard-attributes).

### 2. Make sure your provider *.ingress resolves to your provider IP (ideally worker node IP)
```
host <anything>.ingress.<yourdomain>
```

Example:
```
$ host anything.ingress.akash.pro
anything.ingress.akash.pro is an alias for nodes.akash.pro.
nodes.akash.pro has address 65.108.6.185
```

- More info on what DNS records should look like are available in the [Akash Documentation here](https://docs.akash.network/providers/build-a-cloud-provider/akash-cloud-provider-build-with-helm-charts/step-5-domain-name-review).

### 3. Please make sure your Akash provider doesn't block any Akash specific ports.
   
- If you are using a firewall, please follow this doc:
https://docs.akash.network/providers/build-a-cloud-provider/akash-cloud-provider-build-with-helm-charts/step-9-firewall-rule-review
- If you are behind NAT, then you need to make sure these ports are open between your provider worker nodes and the internet.

# Audit Steps:

**Comment by andy108369** [comment]
- :red_circle:  I am not getting the bids for dseq `13841271`
you can see your provider logs for additional information using this command:
```
kubectl -n akash-services logs akash-provider-0 --tail=1000000 | grep 13841271
```

it is possible that you haven't upgraded your provider for the [mainnet8](https://docs.akash.network/akash-mainnet8-upgrade/mainnet8-provider-upgrade-procedure) yet or your RPC is out of sync, please provide me with the outputs from running these commands:

```
kubectl -n akash-services get pods -o custom-columns='NAME:.metadata.name,IMAGE:.spec.containers[*].image'

kubectl -n akash-services get pods

kubectl get events -A --sort-by='{.metadata.creationTimestamp}'

kubectl get pods -A --sort-by='{.metadata.creationTimestamp}'
```

If you did upgrade to the mainnet8 and your RPC node seem to be working (i.e. indexing the blocks) then you may just need to bounce the akash-provider pod using this command:

```
kubectl -n akash-services delete pod akash-provider-0
```

- :yellow_circle:  you are exposing beta3 storage class, yet you aren't offering it:
```
$ provider-services query provider get akash1whyxrlu7srr55kte4w2rxlmvzduj3je0gqlzjn -o text
...
- key: capabilities/storage/1/class
  value: beta3
- key: capabilities/storage/1/persistent
  value: "true"
- key: capabilities/storage/2/class
  value: beta3
- key: capabilities/storage/2/persistent
  value: "true"
```

this is not a big issue, you can always add it later.
But it is better if you only add these attributes when your provider actually provides the persistent storage.

Also, the 1st class should have `default` value instead of `beta3`, e.g.:

```
- key: capabilities/storage/1/class
  value: default
- key: capabilities/storage/1/persistent
  value: "true"
- key: capabilities/storage/2/class
  value: beta3
- key: capabilities/storage/2/persistent
  value: "true"
```

**Comment by ourlink** [comment]
Can you submit another deployment and check for bids?

I believe our RPC Node was off-line during the last audit testing. We had maintenance scheduled on the node and unfortunately, the tech forgot to restart the server when the network changes were complete. As for now, everything is up and running as expected.

As for our storage classes, we set them to beta3 but the keep defaulting back to SSDHD. Any ideas?

**Comment by ourlink** [comment]
We have this in our provider.yaml file 
```
feat-persistent-storage
true
capabilities/storage/1/class
default
capabilities/storage/1/persistent
true
capabilities/storage/2/class
beta3
capabilities/storage/2/persistent
true
```
But when we look at our listing on the cloudmos.io site we see this (see attached image)
![specs_validatornode](https://github.com/akash-network/support/assets/10887137/6c97d15f-b7af-4e32-9ada-7ee3092d7c1c)
;

**Comment by andy108369** [comment]
## ingress test :green_circle: 

```
$ curl d4stsgbmupd57efiqmet15jk9g.ingress.validatornode.com
<!DOCTYPE html>

$ curl -k https://d4stsgbmupd57efiqmet15jk9g.ingress.validatornode.com
<!DOCTYPE html>
```

## nodePort test :green_circle: 

## speedtest :green_circle: 

```
root@app-b5bb56766-n4fz8:~# speedtest
Retrieving speedtest.net configuration...
Testing from Choopa, LLC (45.77.157.50)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by PFM Host (New York, NY) [42.37 km]: 4.567 ms
Testing download speed................................................................................
Download: 628.07 Mbit/s
Testing upload speed......................................................................................................
Upload: 952.73 Mbit/s
```

## disk speed tests :green_circle: 

```
root@app-b5bb56766-n4fz8:~# curl -sL yabs.sh | bash -s -- -ig
# ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## #
#              Yet-Another-Bench-Script              #
#                     v2023-11-30                    #
# https://github.com/masonr/yet-another-bench-script #
# ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## #

Wed Dec  6 10:02:40 UTC 2023

Basic System Information:
---------------------------------
Uptime     : 7 days, 12 hours, 19 minutes
Processor  : Intel Xeon Processor (Cascadelake)
CPU cores  : 8 @ 2992.968 MHz
AES-NI     : ✔ Enabled
VM-x/AMD-V : ❌ Disabled
RAM        : 15.6 GiB
Swap       : 0.0 KiB
Disk       : 328.1 GiB
Distro     : Ubuntu 22.04.3 LTS
Kernel     : 5.10.0-25-amd64
VM Type    : 
IPv4/IPv6  : ✔ Online / ❌ Offline

IPv4 Network Information:
---------------------------------
ISP        : The Constant Company
ASN        : AS20473 The Constant Company, LLC
Host       : Vultr Holdings, LLC
Location   : Piscataway, New Jersey (NJ)
Country    : United States

fio Disk Speed Tests (Mixed R/W 50/50) (Partition overlay):
---------------------------------
Block Size | 4k            (IOPS) | 64k           (IOPS)
  ------   | ---            ----  | ----           ---- 
Read       | 140.26 MB/s  (35.0k) | 743.30 MB/s  (11.6k)
Write      | 140.63 MB/s  (35.1k) | 747.21 MB/s  (11.6k)
Total      | 280.89 MB/s  (70.2k) | 1.49 GB/s    (23.2k)
           |                      |                     
Block Size | 512k          (IOPS) | 1m            (IOPS)
  ------   | ---            ----  | ----           ---- 
Read       | 1.12 GB/s     (2.1k) | 1.23 GB/s     (1.2k)
Write      | 1.18 GB/s     (2.3k) | 1.32 GB/s     (1.2k)
Total      | 2.30 GB/s     (4.5k) | 2.55 GB/s     (2.4k)

YABS completed in 35 sec
```

## provider signed!

tx `15D4D79DAC53BFD5C92B4A8A8D6C3FF440E62D394A2C6F36DA7C29EF3C1D3A53`



> But when we look at our listing on the cloudmos.io site we see this (see attached image)

For the cloudmos related questions - please seek the support in the [#ecosystem-cloudmos](https://discord.gg/pkSgatVN) Akash Network Devs discord.
