### ISSUE TITLE
[Provider Audit] provider.optize.de

### ISSUE THREAD

**Issue by sbc-mining** [akash-network/support#153]
I have completed all the prerequisite steps as outlined below. If you could review/audit my provider i woud be appreciative.

My contact information:

    -Name: Optize
    -Discord handle: kaal._.
    -Contact email address [kontakt@optize.de](mailto:kontakt@optize.de)

Provider details:

    -URL - https://provider.optize.de:8443
    -Address - akash1f9fldqwcyrfp49m87g8q2zcw7429kphr94k8sv

### 1. Make sure your provider has community provider attributes:

```
  Example:
  $ provider-services query provider get akash1<REDACTED> -o text
  ...
  attributes:
  ...
  - key: host
  value: akash
  - key: tier
  value: community

```

[Ref documentation:](https://docs.akash.network/providers/akash-audited-attributes#standard-attributes).

### 2. Make sure your provider *.ingress resolves to your provider IP (ideally worker node IP)
```
host <anything>.ingress.<yourdomain>
```

Example:
```
$ host anything.ingress.akash.pro
anything.ingress.akash.pro is an alias for nodes.akash.pro.
nodes.akash.pro has address 65.108.6.185
```

- More info on what DNS records should look like are available in the [Akash Documentation here](https://docs.akash.network/providers/build-a-cloud-provider/akash-cloud-provider-build-with-helm-charts/step-5-domain-name-review).

### 3. Please make sure your Akash provider doesn't block any Akash specific ports.
   
- If you are using a firewall, please follow this doc:
https://docs.akash.network/providers/build-a-cloud-provider/akash-cloud-provider-build-with-helm-charts/step-9-firewall-rule-review
- If you are behind NAT, then you need to make sure these ports are open between your provider worker nodes and the internet.

# Audit Steps:

**Comment by andy108369** [comment]
provider `akash1f9fldqwcyrfp49m87g8q2zcw7429kphr94k8sv` signed. TX `E85036C5330C0EF4FE483F370303DBF8A1555FBAC78D574358ABEC23133FBA58`

- provider bids (dseq 14008363)
- creates deployment
- lease-shell, lease-logs OK
- nodePort OK
- ingress OK
- speedtest (network) OK (download 61.28 Mbit/s, upload 47.35 Mbit/s)
- disk speed OK


- speedtest (network) logs
```
root@app-546d57c5bc-xht8x:~# speedtest
Retrieving speedtest.net configuration...
Testing from Vodafone Germany Cable (62.143.185.53)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by SYNLINQ (Frankfurt am Main) [164.11 km]: 42.962 ms
Testing download speed................................................................................
Download: 61.28 Mbit/s
Testing upload speed......................................................................................................
Upload: 47.35 Mbit/s
```

- disk speed logs
```
root@app-546d57c5bc-xht8x:~# curl -sL yabs.sh | bash -s -- -ig
# ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## #
#              Yet-Another-Bench-Script              #
#                     v2023-11-30                    #
# https://github.com/masonr/yet-another-bench-script #
# ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## #

Thu Dec  7 09:38:01 UTC 2023

ARM compatibility is considered *experimental*

Basic System Information:
---------------------------------
Uptime     : 5 days, 1 hours, 40 minutes
Processor  : Cortex-A72
CPU cores  : 4 @ 1900.0000 MHz
AES-NI     : ❌ Disabled
VM-x/AMD-V : ❌ Disabled
RAM        : 7.6 GiB
Swap       : 0.0 KiB
Disk       : 439.8 GiB
Distro     : Ubuntu 22.04.3 LTS
Kernel     : 5.15.0-1043-raspi
VM Type    : 
IPv4/IPv6  : ✔ Online / ❌ Offline

IPv4 Network Information:
---------------------------------
ISP        : Vodafone
ASN        : AS3209 Vodafone GmbH
Host       : Unitymedia Group
Location   : Iserlohn, North Rhine-Westphalia (NW)
Country    : Germany

fio Disk Speed Tests (Mixed R/W 50/50) (Partition overlay):
---------------------------------
Block Size | 4k            (IOPS) | 64k           (IOPS)
  ------   | ---            ----  | ----           ---- 
Read       | 22.95 MB/s    (5.7k) | 122.56 MB/s   (1.9k)
Write      | 22.94 MB/s    (5.7k) | 126.20 MB/s   (1.9k)
Total      | 45.89 MB/s   (11.4k) | 248.77 MB/s   (3.8k)
           |                      |                     
Block Size | 512k          (IOPS) | 1m            (IOPS)
  ------   | ---            ----  | ----           ---- 
Read       | 50.16 MB/s      (97) | 151.98 MB/s    (148)
Write      | 54.45 MB/s     (106) | 169.56 MB/s    (165)
Total      | 104.62 MB/s    (203) | 321.54 MB/s    (313)

YABS completed in 51 sec
```
