### ISSUE TITLE
Akash API documentation (swagger)

### ISSUE THREAD

**Issue by anilmurty** [akash-network/support#159]
https://docs.akash.network/akash-nodes/api-endpoints currently only includes Cosmos SDK APIs and this isn't very helpful for anyone trying to build on or integrate with Akash.

We should enable https://github.com/akash-network/akash-api/blob/main/docs/swagger-ui/swagger.yaml and any other APIs to be viewable in swagger instead and run a hosted instance of the UI (maybe on the colo provider?)

**Comment by troian** [comment]
swagger documentation is off by default.
it can be enabled on each node by either in `app.toml`
```toml
[api]
enable = true
swagger = true
```

or with environment variables:
`AKASH_API_ENABLE=true` `AKASH_API_SWAGGER=true`.

API by default is available on port `1317`
