### ISSUE TITLE
governance: prevent scam proposals

### ISSUE THREAD

**Issue by baktun14** [akash-network/support#16]
Akash has been a victim of scam proposals for a while now and there seems to be a solution implement by osmosis already.

https://twitter.com/sunnya97/status/1620058887578869763

Here's a reference implementation of Juno that will soon be released.

https://github.com/CosmosContracts/juno/blob/main/app/decorators/gov_filter.go

**Comment by andy108369** [comment]
![image](https://user-images.githubusercontent.com/107317698/217112808-c7f7a222-ba33-4a22-9bf4-ee1adc90692b.png)
