### ISSUE TITLE
Typescript protobuf generation

### ISSUE THREAD

**Issue by baktun14** [akash-network/support#184]
### Is your feature request related to a problem? Please describe.

The typescript protobuf generation are currently done in akashjs, while the go ones are done in akash-api. We need to centralize the logic of generating the protobuf types for multiple languages in the same repo (akash-api).

### Describe the solution you'd like

- Move from akashjs and write a script/procedure to generate the typescript types
- Build a npm package from the generated protobuf types
- Import that npm package in akashjs

### Describe alternatives you've considered

This is the best we got!

### Search

- [X] I did search for other open and closed issues before opening this

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by baktun14** [comment]
For rust: #176

**Comment by baktun14** [comment]
- We will probably use Buf https://github.com/bufbuild/buf in favor or ts-proto (to be verified)
- Npm package: Must expose all the protobuf types generated + typeregistry for the npm package
	- @akashnetwork/proto
- Must fix DecCoin? Add tests to validate
	- Original cosmos sdk issue: https://github.com/cosmos/cosmos-sdk/issues/10863
	- https://github.com/akash-network/akashjs/pull/31
- Generate grpc client

**Comment by ygrishajev** [comment]
atm some discussions are done, overall vision is being formed and some initial code has been pushed. Overall it's just started taking into account that I'm getting familiar with akash-api code.

**Comment by baktun14** [comment]
Also [this commit](https://github.com/akash-network/akashjs/commit/c9d75cbf469d23cfba79b2085d34ef1d420357d5#diff-ede7dc9cbf23af844f8b44be0bd3bc0ebaa40021814f1e076fa8b5c828ac5e03) not sure. cc @Redm4x

**Comment by ygrishajev** [comment]
Another issue: akashjs still needs some deprecated generated code for cloudmos. So I'm going to move it to akash-api too to keep separation of concerns proper.
After all this is a common thing that some archived types might be needed. Akash-api makes it a logical location for those

**Comment by ygrishajev** [comment]
All the tech implementation is done. It's uncovered though that there are [examples](https://github.com/akash-network/akashjs/tree/main/examples) that should also be updated as some community members struggle with the implementation.

**Comment by ygrishajev** [comment]
this issue can be closed now
