### ISSUE TITLE
Migrate Node to CometBFT

### ISSUE THREAD

**Issue by PJEstrada** [akash-network/support#20]
**Describe the bug**
The chain needs to be upgraded to use [CometBFT](https://github.com/cometbft/cometbft). This issue can serve as a baseline for tracking progress of other projects in the ecosystem that are going through the same migration, and add any other references that help to better define a plan, and document things to look out before starting the migration

## Existing Projects Migrating Reference

* [Cosmos SDK] https://github.com/cosmos/cosmos-sdk/issues/14870
* Migration Code for Existing modules (check code inside the `x/bank` folder for example). Seems like most of the code is related to import path changes: https://github.com/cosmos/cosmos-sdk/pull/14897/files

## Comptability With Tenderming Core

Currently supported versions include:
v0.34.x: CometBFT v0.34.25 is compatible with Tendermint Core v0.34.24
v0.37.x: (release candidate)

Upgrading Notes from CometBFT: https://github.com/cometbft/cometbft/blob/main/UPGRADING.md

## Notes 
* CometBFT Community Group: [https://groups.google.com/g/cometbft-community/?pli=1](https://groups.google.com/g/cometbft-community/?pli=1&authuser=1)
* If your application is building on the Cosmos SDK: New SDK versions for the 0.45, 0.46 and 0.47 lines will be released by the Cosmos SDK team. These releases will use CometBFT v0.34 instead of Tendermint Core 0.34, per agreement among the Interchain Stack contributors and projects. Upgrading to this SDK version does not require a coordinated upgrade, as it is a minor version change. The [Cosmos SDK changelog ](https://github.com/cosmos/cosmos-sdk/blob/main/CHANGELOG.md) will document the relevant changes for your application. This is from the official communications of informal systems: https://informal.systems/blog/cosmos-meet-cometbft
* From the above, Looks like Migrating the cosmos SDK to these new version will do most of the work for cosmos modules. And since they flagged it as a minor upgrade, which is good news.

**Comment by troian** [comment]
Thanks, @PJEstrada 
Ideally, we need to start with v0.34.21

**Comment by troian** [comment]
refs #77

**Comment by troian** [comment]
it looks like cometBFT is coming to [v0.45.15](https://github.com/cosmos/cosmos-sdk/commit/53db3771bb58909aeeb0d5895fc4ed590b658ad8) so we might include it in the next network upgrade
