### ISSUE TITLE
Build RPC proxy

### ISSUE THREAD

**Issue by troian** [akash-network/support#235]
### Is your feature request related to a problem? Please describe.

cosmos.directory proxy has caps and limitations for usage like Akash console.

### Describe the solution you'd like

Build Go tool that:
1. reads list of available RPC servers from chain [meta file](https://github.com/cosmos/chain-registry/blob/master/akash/chain.json).
  - check each node if it's alive and if the node is not catching up
  - check nodes are reporting correct chain-id
  - calculate ping time overtime
2. `/rpc` endpoint receives requests and proxies them to live nodes
3. Live reload of RPC nodes without the need to restart the server
4. implement authentication via JWT.
  - authenticated clients get best nodes
  - implement caps on unauthenticated clients

### Describe alternatives you've considered

n/a

### Search

- [X] I did search for other open and closed issues before opening this

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by thebigbone** [comment]
Hello, I am working on this. Just had a few questions:
- For checking if the node is alive and catching up, is there anything more required than a simple ping?
- Where do I get the chain-id for a RPC node?
- For ping overtime, what should be duration over which I can show the average ping time?
- Can you explain the third point more clearly?

**Comment by troian** [comment]
hi @thebigbone it was done in https://github.com/akash-network/rpc-proxy

**Comment by troian** [comment]
hi @thebigbone will you be able to implement GRPC part of the proxy?
