### ISSUE TITLE
I sent it to the wrong akash private address

### ISSUE THREAD

**Issue by sollabr** [akash-network/support#258]
### Is your feature request related to a problem? Please describe.

I was carrying out the coinbase missions, and I got to the part of creating the account on keplr and sending 3 akt, I took the money from the missions and what I had already invested in the account and bought it, so far so good, but when it was time to return it from keplr to coinbase, I used the address of the recipient who sent to keplr, thinking it was my account, the address in question is this: akash1ph34j6hlau9v3cgd8npuxpmkvv8wfrj9rnkzx7

### Describe the solution you'd like

I would like the money that I committed to doing the missions and the investment invested in the coin base to return to me, as the 3 akt that I sent to the mentioned address were unintentionally wrong

### Describe alternatives you've considered

I just ask you to give me feedback, I'm waiting and thank you in advance

### Search

- [X] I did search for other open and closed issues before opening this

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

HASH code: 4066A2FA25C6C602CE0EF0C426A65457A5526BD40A349A1BF922076243A340B8
![IMG_2269](https://github.com/user-attachments/assets/5794232a-8c77-4200-9e43-3752763b54c5)
![IMG_2268](https://github.com/user-attachments/assets/8669728a-cf44-41c5-a4e9-2ceff6900673)

photo also of the print referring to the code that sent the 3 akt to me on keplr, which is why I based it on it

![IMG_2271](https://github.com/user-attachments/assets/d4e1c844-3b8c-40eb-bb7f-ec641b9b6703)
![IMG_2270](https://github.com/user-attachments/assets/d663f44c-2eb7-4ff9-ab3c-e427f49c814c)

**Comment by piber-dev** [comment]
some messages related to this are already on discord [here](https://discord.com/channels/747885925232672829/1111760555120808047/1295542440694120520). the response from a vanguard was that you should contact coinbase for support which you mentioned that you did. after this, you mentioned that the address does not belong to coinbase and that you're wondering if core team operates the address (akash1ph34j6hlau9v3cgd8npuxpmkvv8wfrj9rnkzx7). maybe @brewsterdrinkwater who is assigned can look into this?

**Comment by sollabr** [comment]
Thank you for the feedback, that's exactly what happened, I believe
that the wrong address I sent is a contract address, thanks in advance
for the feedback again, until I got here there were many people trying
to steal from me in my discord direct



Em qua., 16 de out. de 2024 às 11:28, piber-dev ***@***.***>
escreveu:

**Comment by troian** [comment]
@sollabr this repo is to track development issues. closing
