### ISSUE TITLE
Bid Storm Mitigation - Max bids pr hour - customizable provider feature.

### ISSUE THREAD

**Issue by SGC41** [akash-network/support#263]
### Is your feature request related to a problem? Please describe.

With the recent Trial super high activity and some recent testing by yours truly.

I enabled USDC again last night, wanted to see just how bad the crazy activity was.... 

Wanted to see if there was any real USDC work, because ATK network has been very quite...... like a few bids every few hours, or so.... very limited maybe 40-70 a day.

So i turned it on and was quickly a bit surprised about just how many bids i was seeing... also because my provider can't get leased, by the trial, due to the whitelist it will keep responding to every bid and thus giving me a clear view of exactly how busy it is.

i was going to check the last 12 or so do the math .... but i found myself nearly unable and atleast unwilling to do this due to the time, it would take with the tools i'm currently using... i'm sure there are much better ways, but i'm not a blockchain engineer.
so what i usually do is count my wallet pages in mintscan, because they have 10 transactions each and then maybe subtract my withdrawals, but since i got 3 lease and a 6 hour withdrawal rate that will be pretty irrelevant.

i counted 104 pages in the last 3 hours... that would make it 8160 bids in a 24 hour period. 

hench 8160 x 0.004 = 32 AKT a day or 78$ a day
2340 $ a month in bidding fees....
🆘 📛

 .... bid storms ... for a lack of a better definition.

if one has hardware that isn't being selected and the bids are not very hardware restrictive, many providers might still bid...

### Describe the solution you'd like

i would suggest we need a sort of customizable bid delay / max per hour in our provider.yaml
so we could set a provider to not bid more than is reasonable for, what it can earn...

### Describe alternatives you've considered

duno if this is the best solution for this.... i'm ofc open to better ideas.
but its what i got thus far

### Search

- [X] I did search for other open and closed issues before opening this

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chainzero** [comment]
Immediate issue/concern and as it pertains to Trial bids has been addressed by provider signed attributes.  I.e. the only providers on the network that will bid on trial workloads are those that are participating in Akash Trials.  This spares community providers that are not part of the program from associated bid fees.

This leaves the remaining question - is there sufficient need or cause to protect providers from bid storms otherwise.  There are other safeguards in place - such as provider pricing script adjustments to eliminate bidding on small workloads if desired.

**Comment by SGC41** [comment]
seems to work for now...

still think there is a bit of a deeper issue, that may need to be addressed in the future.
its not difficult to imagine a trial provider, not being favored by the deployers, which would lead to such providers paying excessive fees.

that being said, this would be a pretty rare event, and for all the non trial providers, this solution works great.
so closing the issue.

**Comment by SGC41** [comment]
seems to work for now...

still think there is a bit of a deeper issue, that may need to be addressed in the future.
its not difficult to imagine a trial provider, not being favored by the deployers, which would lead to such providers paying excessive fees.

that being said, this would be a pretty rare event, and for all the non trial providers, this solution works great.
so closing the issue.
