### ISSUE TITLE
too many existing bids (20)

### ISSUE THREAD

**Issue by andy108369** [akash-network/support#28]
akash v0.16.4

continuing https://github.com/ovrclk/akash/issues/1660 here

1. more than 20 open bids across all providers:

```
$ akash query market bid list --state open | grep dseq | wc -l
23
```

2. 0 open bids for the provider (AMS1):

```
$ akash query market bid list --state open --provider akash14c4ng96vdle6tae8r4hc2w4ujwrsh3x9tuudk0 | grep dseq | wc -l
0
```

3. AMS1 provider has 0 pending order:

```
$ curl -s -k https://provider.provider-0.prod.ams1.akash.pub:8443/status | jq -r '[.cluster.leases, (.cluster.inventory.active|length), .bidengine.orders, .manifest.deployments] | @csv'
39,39,0,0
```

4. seeing only my order request for AMS1 provider:

```
$ akash query market bid list --state open --provider akash14c4ng96vdle6tae8r4hc2w4ujwrsh3x9tuudk0 | grep dseq | wc -l
1
```

5. provider gets `too many existing bids (20): unknown provider`

```
$ akash query tx 4E7D3B9EC2C821F81AAE473D7AAD68643D38D2772904700914D2C5D9766F10C7 -o json | jq -r '.raw_log'
failed to execute message; message index: 0: too many existing bids (20): unknown provider
```

Probably worth noting that this, somehow, works better when not using a state-sync RPC node. I.e. I have not hit this issue each time I switched from state-sync RPC node back to the full (archive) RPC node. Or maybe I just hit the right point in time.

I'll leave AMS1 with state-sync RPC node for now.

https://www.mintscan.io/akash/txs/4E7D3B9EC2C821F81AAE473D7AAD68643D38D2772904700914D2C5D9766F10C7
https://www.mintscan.io/akash/txs/6A81D3845A71B1F12FB32EF4290EDB6A04943D1EE07E1A7285E6C28994A76245

**Comment by troian** [comment]
@andy108369 lets format the description and put it in the [proposals section](https://github.com/orgs/akash-network/discussions/categories/governance-proposals)

**Comment by andy108369** [comment]
> @andy108369 lets format the description and put it in the [proposals section](https://github.com/orgs/akash-network/discussions/categories/governance-proposals)

=> https://github.com/orgs/akash-network/discussions/149

**Comment by andy108369** [comment]
proposal broadcasted => https://www.mintscan.io/akash/proposals/197

**Comment by andy108369** [comment]
Proposal #197 passed!
The `OrderMaxBids` parameter has been updated from `20` to `50`.

```
$ akash query gov proposal 197 -o json | jq -r '.status, .voting_end_time'
PROPOSAL_STATUS_PASSED
2023-04-12T19:03:20.032599861Z

$ akash query block 10594876 | jq -r '.block.header.time'
2023-04-12T19:03:14.999700372Z

$ akash --height 10594876 query params subspace market OrderMaxBids -o json | jq
{
  "subspace": "market",
  "key": "OrderMaxBids",
  "value": "20"
}

$ akash query block 10594877 | jq -r '.block.header.time'
2023-04-12T19:03:20.874033546Z

$ akash --height 10594877 query params subspace market OrderMaxBids -o json | jq
{
  "subspace": "market",
  "key": "OrderMaxBids",
  "value": "50"
}
```
