### ISSUE TITLE
`provider-statefulset-restart` not supported on ARM64

### ISSUE THREAD

**Issue by cloud-j-luna** [akash-network/support#5]
The `provider-statefulset-restart` cronjob is not supported on `arm64` due to the fact that it uses `bitnami/kubectl` docker image and it does not yet have an `arm64` version. An alternative would be the `rancher/kubectl` docker image which does support `arm64`. This can be achieved by changing the image depending on the host's system.

**Comment by andy108369** [comment]
Good catch!
`rancher/kubectl` sounds like a better option! :)
