### ISSUE TITLE
sig-chain: network upgrade v0.24.0

### ISSUE THREAD

**Issue by troian** [akash-network/support#73]
This issue covers store changes to be performed during the `v0.24.0` upgrade

### Resource units
Add GPU object consisting of `Units` and `Attributes` fields.
Add GPU object to the `ResourceUnits`
Those changes are implemented [here](https://github.com/akash-network/akash-api/pull/1)

### Gov
Add a new parameter to the governance module that requires the account originating a new proposal to deposit a certain amount in order for the proposal to be listed on the network.
The parameter's value is a percentage of the existing `min deposit` parameter.
Proposed name of the parameter `min_deposit_on_proposal_create_percent`.

The parameter is defined [here](https://github.com/akash-network/akash-api/pull/4)

### Staking
As [proposal](https://www.mintscan.io/akash/proposals/26) passed all validators need to set minimum commission.
The most beneficial way is to do so by adding a new parameter to the staking module defining the minimum validator's commission.
The proposed name of the parameter is `min_validator_commission_percent`.

The parameter is defined [here](https://github.com/akash-network/akash-api/pull/3)

## Migrations
Set the value of `min_deposit_on_proposal_create_percent` to **TBD**
Set the value of `min_validator_commission_percent` to `5%`

### Staking
Apply `min_validator_commission_percent` to all validators with a commission lower than this value.

**Comment by anilmurty** [comment]
migration to cometBFT will occur as part of the migration to the informal systems fork tendermint

**Comment by anilmurty** [comment]
ref: #23 needs to be fixed before this network upgrade as well

**Comment by troian** [comment]
completed
