### ISSUE TITLE
Enable Authz to cover gas fees

### ISSUE THREAD

**Issue by heyhewi** [akash-network/support#83]
Right now when a user is Authz'd funds from another user, they still need a small amount of AKT for Gas to create a deployment. This user experience is cumbersome for the person receiving funds because they still have to do multiple actions to get AKT to use those funds.

Fix:
Enable Authz to cover all costs related to a deployment for a better user experience.

**Comment by troian** [comment]
the `Authz fee grant` will be included in the v0.24.0
